// Decompiled with JetBrains decompiler
// Type: Terraria.Initializers.AchievementInitializer
// Assembly: Terraria, Version=1.4.0.5, Culture=neutral, PublicKeyToken=null
// MVID: 67F9E73E-0A81-4937-A22C-5515CD405A83
// Assembly location: C:\Users\mikeyisbaeyt\Downloads\depotdownloader-2.4.5\depots\105601\6707058\Terraria.exe

using Terraria.Achievements;
using Terraria.Audio;
using Terraria.GameContent.Achievements;
using Terraria.GameContent.UI.Chat;
using Terraria.ID;
using Terraria.Localization;

namespace Terraria.Initializers
{
  public class AchievementInitializer
  {
    public static void Load()
    {
      if (Main.netMode == 2)
        return;
      Achievement achievement1 = new Achievement("TIMBER");
      achievement1.AddCondition(ItemPickupCondition.Create((short) 9, (short) 619, (short) 2504, (short) 620, (short) 2503, (short) 2260, (short) 621, (short) 911, (short) 1729));
      Main.Achievements.Register(achievement1);
      Achievement achievement2 = new Achievement("BENCHED");
      achievement2.AddCondition(ItemCraftCondition.Create(ItemID.Sets.Workbenches));
      Main.Achievements.Register(achievement2);
      Achievement achievement3 = new Achievement("NO_HOBO");
      achievement3.AddCondition((AchievementCondition) ProgressionEventCondition.Create(8));
      Main.Achievements.Register(achievement3);
      Achievement achievement4 = new Achievement("OBTAIN_HAMMER");
      achievement4.AddCondition(ItemPickupCondition.Create((short) 2775, (short) 2746, (short) 3505, (short) 654, (short) 3517, (short) 7, (short) 3493, (short) 2780, (short) 1513, (short) 2516, (short) 660, (short) 3481, (short) 657, (short) 922, (short) 3511, (short) 2785, (short) 3499, (short) 3487, (short) 196, (short) 367, (short) 104, (short) 797, (short) 2320, (short) 787, (short) 1234, (short) 1262, (short) 3465, (short) 204, (short) 217, (short) 1507, (short) 3524, (short) 3522, (short) 3525, (short) 3523, (short) 4317, (short) 1305));
      Main.Achievements.Register(achievement4);
      Achievement achievement5 = new Achievement("OOO_SHINY");
      achievement5.AddCondition(TileDestroyedCondition.Create((ushort) 7, (ushort) 6, (ushort) 9, (ushort) 8, (ushort) 166, (ushort) 167, (ushort) 168, (ushort) 169, (ushort) 22, (ushort) 204, (ushort) 58, (ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223, (ushort) 211));
      Main.Achievements.Register(achievement5);
      Achievement achievement6 = new Achievement("HEART_BREAKER");
      achievement6.AddCondition(TileDestroyedCondition.Create((ushort) 12));
      Main.Achievements.Register(achievement6);
      Achievement achievement7 = new Achievement("HEAVY_METAL");
      achievement7.AddCondition(ItemPickupCondition.Create((short) 35, (short) 716));
      Main.Achievements.Register(achievement7);
      Achievement achievement8 = new Achievement("I_AM_LOOT");
      achievement8.AddCondition(CustomFlagCondition.Create("Peek"));
      Main.Achievements.Register(achievement8);
      Achievement achievement9 = new Achievement("STAR_POWER");
      achievement9.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement9);
      Achievement achievement10 = new Achievement("HOLD_ON_TIGHT");
      achievement10.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement10);
      Achievement achievement11 = new Achievement("EYE_ON_YOU");
      achievement11.AddCondition(NPCKilledCondition.Create((short) 4));
      Main.Achievements.Register(achievement11);
      Achievement achievement12 = new Achievement("SMASHING_POPPET");
      achievement12.AddCondition((AchievementCondition) ProgressionEventCondition.Create(7));
      Main.Achievements.Register(achievement12);
      Achievement achievement13 = new Achievement("WORM_FODDER");
      achievement13.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
      Main.Achievements.Register(achievement13);
      Achievement achievement14 = new Achievement("MASTERMIND");
      achievement14.AddCondition(NPCKilledCondition.Create((short) 266));
      Main.Achievements.Register(achievement14);
      Achievement achievement15 = new Achievement("WHERES_MY_HONEY");
      achievement15.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement15);
      Achievement achievement16 = new Achievement("STING_OPERATION");
      achievement16.AddCondition(NPCKilledCondition.Create((short) 222));
      Main.Achievements.Register(achievement16);
      Achievement achievement17 = new Achievement("BONED");
      achievement17.AddCondition(NPCKilledCondition.Create((short) 35));
      Main.Achievements.Register(achievement17);
      Achievement achievement18 = new Achievement("DUNGEON_HEIST");
      achievement18.AddCondition(ItemPickupCondition.Create((short) 327));
      achievement18.AddCondition((AchievementCondition) ProgressionEventCondition.Create(19));
      Main.Achievements.Register(achievement18);
      Achievement achievement19 = new Achievement("ITS_GETTING_HOT_IN_HERE");
      achievement19.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement19);
      Achievement achievement20 = new Achievement("MINER_FOR_FIRE");
      achievement20.AddCondition(ItemCraftCondition.Create((short) 122));
      Main.Achievements.Register(achievement20);
      Achievement achievement21 = new Achievement("STILL_HUNGRY");
      achievement21.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
      Main.Achievements.Register(achievement21);
      Achievement achievement22 = new Achievement("ITS_HARD");
      achievement22.AddCondition((AchievementCondition) ProgressionEventCondition.Create(9));
      Main.Achievements.Register(achievement22);
      Achievement achievement23 = new Achievement("BEGONE_EVIL");
      achievement23.AddCondition((AchievementCondition) ProgressionEventCondition.Create(6));
      Main.Achievements.Register(achievement23);
      Achievement achievement24 = new Achievement("EXTRA_SHINY");
      achievement24.AddCondition(TileDestroyedCondition.Create((ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223));
      Main.Achievements.Register(achievement24);
      Achievement achievement25 = new Achievement("HEAD_IN_THE_CLOUDS");
      achievement25.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement25);
      Achievement achievement26 = new Achievement("LIKE_A_BOSS");
      achievement26.AddCondition(ItemPickupCondition.Create((short) 1133, (short) 1331, (short) 1307, (short) 267, (short) 1293, (short) 557, (short) 544, (short) 556, (short) 560, (short) 43, (short) 70));
      Main.Achievements.Register(achievement26);
      Achievement achievement27 = new Achievement("BUCKETS_OF_BOLTS");
      achievement27.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
      achievement27.AddConditions(NPCKilledCondition.CreateMany((short) sbyte.MaxValue, (short) 134));
      achievement27.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement27);
      Achievement achievement28 = new Achievement("DRAX_ATTAX");
      achievement28.AddCondition(ItemCraftCondition.Create((short) 579, (short) 990));
      Main.Achievements.Register(achievement28);
      Achievement achievement29 = new Achievement("PHOTOSYNTHESIS");
      achievement29.AddCondition(TileDestroyedCondition.Create((ushort) 211));
      Main.Achievements.Register(achievement29);
      Achievement achievement30 = new Achievement("GET_A_LIFE");
      achievement30.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement30);
      Achievement achievement31 = new Achievement("THE_GREAT_SOUTHERN_PLANTKILL");
      achievement31.AddCondition(NPCKilledCondition.Create((short) 262));
      Main.Achievements.Register(achievement31);
      Achievement achievement32 = new Achievement("TEMPLE_RAIDER");
      achievement32.AddCondition((AchievementCondition) ProgressionEventCondition.Create(22));
      Main.Achievements.Register(achievement32);
      Achievement achievement33 = new Achievement("LIHZAHRDIAN_IDOL");
      achievement33.AddCondition(NPCKilledCondition.Create((short) 245));
      Main.Achievements.Register(achievement33);
      Achievement achievement34 = new Achievement("ROBBING_THE_GRAVE");
      achievement34.AddCondition(ItemPickupCondition.Create((short) 1513, (short) 938, (short) 963, (short) 977, (short) 1300, (short) 1254, (short) 1514, (short) 679, (short) 759, (short) 1446, (short) 1445, (short) 1444, (short) 1183, (short) 1266, (short) 671, (short) 3291, (short) 4679));
      Main.Achievements.Register(achievement34);
      Achievement achievement35 = new Achievement("BIG_BOOTY");
      achievement35.AddCondition((AchievementCondition) ProgressionEventCondition.Create(20));
      Main.Achievements.Register(achievement35);
      Achievement achievement36 = new Achievement("FISH_OUT_OF_WATER");
      achievement36.AddCondition(NPCKilledCondition.Create((short) 370));
      Main.Achievements.Register(achievement36);
      Achievement achievement37 = new Achievement("OBSESSIVE_DEVOTION");
      achievement37.AddCondition(NPCKilledCondition.Create((short) 439));
      Main.Achievements.Register(achievement37);
      Achievement achievement38 = new Achievement("STAR_DESTROYER");
      achievement38.AddConditions(NPCKilledCondition.CreateMany((short) 517, (short) 422, (short) 507, (short) 493));
      Main.Achievements.Register(achievement38);
      Achievement achievement39 = new Achievement("CHAMPION_OF_TERRARIA");
      achievement39.AddCondition(NPCKilledCondition.Create((short) 398));
      Main.Achievements.Register(achievement39);
      Achievement achievement40 = new Achievement("BLOODBATH");
      achievement40.AddCondition((AchievementCondition) ProgressionEventCondition.Create(5));
      Main.Achievements.Register(achievement40);
      Achievement achievement41 = new Achievement("SLIPPERY_SHINOBI");
      achievement41.AddCondition(NPCKilledCondition.Create((short) 50));
      Main.Achievements.Register(achievement41);
      Achievement achievement42 = new Achievement("GOBLIN_PUNTER");
      achievement42.AddCondition((AchievementCondition) ProgressionEventCondition.Create(10));
      Main.Achievements.Register(achievement42);
      Achievement achievement43 = new Achievement("WALK_THE_PLANK");
      achievement43.AddCondition((AchievementCondition) ProgressionEventCondition.Create(11));
      Main.Achievements.Register(achievement43);
      Achievement achievement44 = new Achievement("KILL_THE_SUN");
      achievement44.AddCondition((AchievementCondition) ProgressionEventCondition.Create(3));
      Main.Achievements.Register(achievement44);
      Achievement achievement45 = new Achievement("DO_YOU_WANT_TO_SLAY_A_SNOWMAN");
      achievement45.AddCondition((AchievementCondition) ProgressionEventCondition.Create(12));
      Main.Achievements.Register(achievement45);
      Achievement achievement46 = new Achievement("TIN_FOIL_HATTER");
      achievement46.AddCondition((AchievementCondition) ProgressionEventCondition.Create(13));
      Main.Achievements.Register(achievement46);
      Achievement achievement47 = new Achievement("BALEFUL_HARVEST");
      achievement47.AddCondition((AchievementCondition) ProgressionEventCondition.Create(15));
      Main.Achievements.Register(achievement47);
      Achievement achievement48 = new Achievement("ICE_SCREAM");
      achievement48.AddCondition((AchievementCondition) ProgressionEventCondition.Create(14));
      Main.Achievements.Register(achievement48);
      Achievement achievement49 = new Achievement("STICKY_SITUATION");
      achievement49.AddCondition((AchievementCondition) ProgressionEventCondition.Create(16));
      Main.Achievements.Register(achievement49);
      Achievement achievement50 = new Achievement("REAL_ESTATE_AGENT");
      achievement50.AddCondition((AchievementCondition) ProgressionEventCondition.Create(17));
      Main.Achievements.Register(achievement50);
      Achievement achievement51 = new Achievement("NOT_THE_BEES");
      achievement51.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement51);
      Achievement achievement52 = new Achievement("JEEPERS_CREEPERS");
      achievement52.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement52);
      Achievement achievement53 = new Achievement("FUNKYTOWN");
      achievement53.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement53);
      Achievement achievement54 = new Achievement("INTO_ORBIT");
      achievement54.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement54);
      Achievement achievement55 = new Achievement("ROCK_BOTTOM");
      achievement55.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement55);
      Achievement achievement56 = new Achievement("MECHA_MAYHEM");
      achievement56.AddCondition((AchievementCondition) ProgressionEventCondition.Create(21));
      Main.Achievements.Register(achievement56);
      Achievement achievement57 = new Achievement("GELATIN_WORLD_TOUR");
      achievement57.AddConditions(NPCKilledCondition.CreateMany((short) -5, (short) -6, (short) 1, (short) 81, (short) 71, (short) -3, (short) 147, (short) 138, (short) -10, (short) 50, (short) 59, (short) 16, (short) -7, (short) 244, (short) -8, (short) -1, (short) -2, (short) 184, (short) 204, (short) 225, (short) -9, (short) 141, (short) 183, (short) -4));
      achievement57.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement57);
      Achievement achievement58 = new Achievement("FASHION_STATEMENT");
      achievement58.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement58);
      Achievement achievement59 = new Achievement("VEHICULAR_MANSLAUGHTER");
      achievement59.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement59);
      Achievement achievement60 = new Achievement("BULLDOZER");
      achievement60.AddCondition(CustomIntCondition.Create("Pick", 10000));
      achievement60.UseTrackerFromCondition("Pick");
      Main.Achievements.Register(achievement60);
      Achievement achievement61 = new Achievement("THERE_ARE_SOME_WHO_CALL_HIM");
      achievement61.AddCondition(NPCKilledCondition.Create((short) 45));
      Main.Achievements.Register(achievement61);
      Achievement achievement62 = new Achievement("DECEIVER_OF_FOOLS");
      achievement62.AddCondition(NPCKilledCondition.Create((short) 196));
      Main.Achievements.Register(achievement62);
      Achievement achievement63 = new Achievement("SWORD_OF_THE_HERO");
      achievement63.AddCondition(ItemPickupCondition.Create((short) 757));
      Main.Achievements.Register(achievement63);
      Achievement achievement64 = new Achievement("LUCKY_BREAK");
      achievement64.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement64);
      Achievement achievement65 = new Achievement("THROWING_LINES");
      achievement65.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement65);
      Achievement achievement66 = new Achievement("DYE_HARD");
      achievement66.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement66);
      Achievement achievement67 = new Achievement("SICK_THROW");
      achievement67.AddCondition(ItemPickupCondition.Create((short) 3389));
      Main.Achievements.Register(achievement67);
      Achievement achievement68 = new Achievement("FREQUENT_FLYER");
      achievement68.AddCondition(CustomFloatCondition.Create("Pay", 10000f));
      achievement68.UseTrackerFromCondition("Pay");
      Main.Achievements.Register(achievement68);
      Achievement achievement69 = new Achievement("THE_CAVALRY");
      achievement69.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement69);
      Achievement achievement70 = new Achievement("COMPLETELY_AWESOME");
      achievement70.AddCondition(ItemPickupCondition.Create((short) 98));
      Main.Achievements.Register(achievement70);
      Achievement achievement71 = new Achievement("TIL_DEATH");
      achievement71.AddCondition(NPCKilledCondition.Create((short) 53));
      Main.Achievements.Register(achievement71);
      Achievement achievement72 = new Achievement("ARCHAEOLOGIST");
      achievement72.AddCondition(NPCKilledCondition.Create((short) 52));
      Main.Achievements.Register(achievement72);
      Achievement achievement73 = new Achievement("PRETTY_IN_PINK");
      achievement73.AddCondition(NPCKilledCondition.Create((short) -4));
      Main.Achievements.Register(achievement73);
      Achievement achievement74 = new Achievement("RAINBOWS_AND_UNICORNS");
      achievement74.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement74);
      Achievement achievement75 = new Achievement("YOU_AND_WHAT_ARMY");
      achievement75.AddCondition(CustomFlagCondition.Create("Spawn"));
      Main.Achievements.Register(achievement75);
      Achievement achievement76 = new Achievement("PRISMANCER");
      achievement76.AddCondition(ItemPickupCondition.Create((short) 495));
      Main.Achievements.Register(achievement76);
      Achievement achievement77 = new Achievement("IT_CAN_TALK");
      achievement77.AddCondition((AchievementCondition) ProgressionEventCondition.Create(18));
      Main.Achievements.Register(achievement77);
      Achievement achievement78 = new Achievement("WATCH_YOUR_STEP");
      achievement78.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement78);
      Achievement achievement79 = new Achievement("MARATHON_MEDALIST");
      achievement79.AddCondition(CustomFloatCondition.Create("Move", 1106688f));
      achievement79.UseTrackerFromCondition("Move");
      Main.Achievements.Register(achievement79);
      Achievement achievement80 = new Achievement("GLORIOUS_GOLDEN_POLE");
      achievement80.AddCondition(ItemPickupCondition.Create((short) 2294));
      Main.Achievements.Register(achievement80);
      Achievement achievement81 = new Achievement("SERVANT_IN_TRAINING");
      achievement81.AddCondition(CustomFlagCondition.Create("Finish"));
      Main.Achievements.Register(achievement81);
      Achievement achievement82 = new Achievement("GOOD_LITTLE_SLAVE");
      achievement82.AddCondition(CustomIntCondition.Create("Finish", 10));
      achievement82.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement82);
      Achievement achievement83 = new Achievement("TROUT_MONKEY");
      achievement83.AddCondition(CustomIntCondition.Create("Finish", 25));
      achievement83.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement83);
      Achievement achievement84 = new Achievement("FAST_AND_FISHIOUS");
      achievement84.AddCondition(CustomIntCondition.Create("Finish", 50));
      achievement84.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement84);
      Achievement achievement85 = new Achievement("SUPREME_HELPER_MINION");
      achievement85.AddCondition(CustomIntCondition.Create("Finish", 200));
      achievement85.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement85);
      Achievement achievement86 = new Achievement("TOPPED_OFF");
      achievement86.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement86);
      Achievement achievement87 = new Achievement("SLAYER_OF_WORLDS");
      achievement87.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
      achievement87.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
      achievement87.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
      achievement87.AddConditions(NPCKilledCondition.CreateMany((short) 4, (short) 266, (short) 35, (short) 50, (short) 222, (short) 134, (short) sbyte.MaxValue, (short) 262, (short) 245, (short) 439, (short) 398, (short) 370));
      achievement87.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement87);
      Achievement achievement88 = new Achievement("YOU_CAN_DO_IT");
      achievement88.AddCondition((AchievementCondition) ProgressionEventCondition.Create(1));
      Main.Achievements.Register(achievement88);
      Achievement achievement89 = new Achievement("MATCHING_ATTIRE");
      achievement89.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement89);
      int num1 = 0;
      AchievementManager achievements1 = Main.Achievements;
      int iconIndex1 = num1;
      int num2 = iconIndex1 + 1;
      achievements1.RegisterIconIndex("TIMBER", iconIndex1);
      AchievementManager achievements2 = Main.Achievements;
      int iconIndex2 = num2;
      int num3 = iconIndex2 + 1;
      achievements2.RegisterIconIndex("NO_HOBO", iconIndex2);
      AchievementManager achievements3 = Main.Achievements;
      int iconIndex3 = num3;
      int num4 = iconIndex3 + 1;
      achievements3.RegisterIconIndex("OBTAIN_HAMMER", iconIndex3);
      AchievementManager achievements4 = Main.Achievements;
      int iconIndex4 = num4;
      int num5 = iconIndex4 + 1;
      achievements4.RegisterIconIndex("HEART_BREAKER", iconIndex4);
      AchievementManager achievements5 = Main.Achievements;
      int iconIndex5 = num5;
      int num6 = iconIndex5 + 1;
      achievements5.RegisterIconIndex("OOO_SHINY", iconIndex5);
      AchievementManager achievements6 = Main.Achievements;
      int iconIndex6 = num6;
      int num7 = iconIndex6 + 1;
      achievements6.RegisterIconIndex("HEAVY_METAL", iconIndex6);
      AchievementManager achievements7 = Main.Achievements;
      int iconIndex7 = num7;
      int num8 = iconIndex7 + 1;
      achievements7.RegisterIconIndex("I_AM_LOOT", iconIndex7);
      AchievementManager achievements8 = Main.Achievements;
      int iconIndex8 = num8;
      int num9 = iconIndex8 + 1;
      achievements8.RegisterIconIndex("STAR_POWER", iconIndex8);
      AchievementManager achievements9 = Main.Achievements;
      int iconIndex9 = num9;
      int num10 = iconIndex9 + 1;
      achievements9.RegisterIconIndex("HOLD_ON_TIGHT", iconIndex9);
      AchievementManager achievements10 = Main.Achievements;
      int iconIndex10 = num10;
      int num11 = iconIndex10 + 1;
      achievements10.RegisterIconIndex("EYE_ON_YOU", iconIndex10);
      AchievementManager achievements11 = Main.Achievements;
      int iconIndex11 = num11;
      int num12 = iconIndex11 + 1;
      achievements11.RegisterIconIndex("SMASHING_POPPET", iconIndex11);
      AchievementManager achievements12 = Main.Achievements;
      int iconIndex12 = num12;
      int num13 = iconIndex12 + 1;
      achievements12.RegisterIconIndex("WORM_FODDER", iconIndex12);
      AchievementManager achievements13 = Main.Achievements;
      int iconIndex13 = num13;
      int num14 = iconIndex13 + 1;
      achievements13.RegisterIconIndex("MASTERMIND", iconIndex13);
      AchievementManager achievements14 = Main.Achievements;
      int iconIndex14 = num14;
      int num15 = iconIndex14 + 1;
      achievements14.RegisterIconIndex("WHERES_MY_HONEY", iconIndex14);
      AchievementManager achievements15 = Main.Achievements;
      int iconIndex15 = num15;
      int num16 = iconIndex15 + 1;
      achievements15.RegisterIconIndex("STING_OPERATION", iconIndex15);
      AchievementManager achievements16 = Main.Achievements;
      int iconIndex16 = num16;
      int num17 = iconIndex16 + 1;
      achievements16.RegisterIconIndex("BONED", iconIndex16);
      AchievementManager achievements17 = Main.Achievements;
      int iconIndex17 = num17;
      int num18 = iconIndex17 + 1;
      achievements17.RegisterIconIndex("DUNGEON_HEIST", iconIndex17);
      AchievementManager achievements18 = Main.Achievements;
      int iconIndex18 = num18;
      int num19 = iconIndex18 + 1;
      achievements18.RegisterIconIndex("ITS_GETTING_HOT_IN_HERE", iconIndex18);
      AchievementManager achievements19 = Main.Achievements;
      int iconIndex19 = num19;
      int num20 = iconIndex19 + 1;
      achievements19.RegisterIconIndex("MINER_FOR_FIRE", iconIndex19);
      AchievementManager achievements20 = Main.Achievements;
      int iconIndex20 = num20;
      int num21 = iconIndex20 + 1;
      achievements20.RegisterIconIndex("STILL_HUNGRY", iconIndex20);
      AchievementManager achievements21 = Main.Achievements;
      int iconIndex21 = num21;
      int num22 = iconIndex21 + 1;
      achievements21.RegisterIconIndex("ITS_HARD", iconIndex21);
      AchievementManager achievements22 = Main.Achievements;
      int iconIndex22 = num22;
      int num23 = iconIndex22 + 1;
      achievements22.RegisterIconIndex("BEGONE_EVIL", iconIndex22);
      AchievementManager achievements23 = Main.Achievements;
      int iconIndex23 = num23;
      int num24 = iconIndex23 + 1;
      achievements23.RegisterIconIndex("EXTRA_SHINY", iconIndex23);
      AchievementManager achievements24 = Main.Achievements;
      int iconIndex24 = num24;
      int num25 = iconIndex24 + 1;
      achievements24.RegisterIconIndex("HEAD_IN_THE_CLOUDS", iconIndex24);
      AchievementManager achievements25 = Main.Achievements;
      int iconIndex25 = num25;
      int num26 = iconIndex25 + 1;
      achievements25.RegisterIconIndex("LIKE_A_BOSS", iconIndex25);
      AchievementManager achievements26 = Main.Achievements;
      int iconIndex26 = num26;
      int num27 = iconIndex26 + 1;
      achievements26.RegisterIconIndex("BUCKETS_OF_BOLTS", iconIndex26);
      AchievementManager achievements27 = Main.Achievements;
      int iconIndex27 = num27;
      int num28 = iconIndex27 + 1;
      achievements27.RegisterIconIndex("DRAX_ATTAX", iconIndex27);
      AchievementManager achievements28 = Main.Achievements;
      int iconIndex28 = num28;
      int num29 = iconIndex28 + 1;
      achievements28.RegisterIconIndex("PHOTOSYNTHESIS", iconIndex28);
      AchievementManager achievements29 = Main.Achievements;
      int iconIndex29 = num29;
      int num30 = iconIndex29 + 1;
      achievements29.RegisterIconIndex("GET_A_LIFE", iconIndex29);
      AchievementManager achievements30 = Main.Achievements;
      int iconIndex30 = num30;
      int num31 = iconIndex30 + 1;
      achievements30.RegisterIconIndex("THE_GREAT_SOUTHERN_PLANTKILL", iconIndex30);
      AchievementManager achievements31 = Main.Achievements;
      int iconIndex31 = num31;
      int num32 = iconIndex31 + 1;
      achievements31.RegisterIconIndex("TEMPLE_RAIDER", iconIndex31);
      AchievementManager achievements32 = Main.Achievements;
      int iconIndex32 = num32;
      int num33 = iconIndex32 + 1;
      achievements32.RegisterIconIndex("LIHZAHRDIAN_IDOL", iconIndex32);
      AchievementManager achievements33 = Main.Achievements;
      int iconIndex33 = num33;
      int num34 = iconIndex33 + 1;
      achievements33.RegisterIconIndex("ROBBING_THE_GRAVE", iconIndex33);
      AchievementManager achievements34 = Main.Achievements;
      int iconIndex34 = num34;
      int num35 = iconIndex34 + 1;
      achievements34.RegisterIconIndex("BIG_BOOTY", iconIndex34);
      AchievementManager achievements35 = Main.Achievements;
      int iconIndex35 = num35;
      int num36 = iconIndex35 + 1;
      achievements35.RegisterIconIndex("FISH_OUT_OF_WATER", iconIndex35);
      AchievementManager achievements36 = Main.Achievements;
      int iconIndex36 = num36;
      int num37 = iconIndex36 + 1;
      achievements36.RegisterIconIndex("OBSESSIVE_DEVOTION", iconIndex36);
      AchievementManager achievements37 = Main.Achievements;
      int iconIndex37 = num37;
      int num38 = iconIndex37 + 1;
      achievements37.RegisterIconIndex("STAR_DESTROYER", iconIndex37);
      AchievementManager achievements38 = Main.Achievements;
      int iconIndex38 = num38;
      int num39 = iconIndex38 + 1;
      achievements38.RegisterIconIndex("CHAMPION_OF_TERRARIA", iconIndex38);
      AchievementManager achievements39 = Main.Achievements;
      int iconIndex39 = num39;
      int num40 = iconIndex39 + 1;
      achievements39.RegisterIconIndex("BLOODBATH", iconIndex39);
      AchievementManager achievements40 = Main.Achievements;
      int iconIndex40 = num40;
      int num41 = iconIndex40 + 1;
      achievements40.RegisterIconIndex("GOBLIN_PUNTER", iconIndex40);
      AchievementManager achievements41 = Main.Achievements;
      int iconIndex41 = num41;
      int num42 = iconIndex41 + 1;
      achievements41.RegisterIconIndex("KILL_THE_SUN", iconIndex41);
      AchievementManager achievements42 = Main.Achievements;
      int iconIndex42 = num42;
      int num43 = iconIndex42 + 1;
      achievements42.RegisterIconIndex("WALK_THE_PLANK", iconIndex42);
      AchievementManager achievements43 = Main.Achievements;
      int iconIndex43 = num43;
      int num44 = iconIndex43 + 1;
      achievements43.RegisterIconIndex("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", iconIndex43);
      AchievementManager achievements44 = Main.Achievements;
      int iconIndex44 = num44;
      int num45 = iconIndex44 + 1;
      achievements44.RegisterIconIndex("TIN_FOIL_HATTER", iconIndex44);
      AchievementManager achievements45 = Main.Achievements;
      int iconIndex45 = num45;
      int num46 = iconIndex45 + 1;
      achievements45.RegisterIconIndex("BALEFUL_HARVEST", iconIndex45);
      AchievementManager achievements46 = Main.Achievements;
      int iconIndex46 = num46;
      int num47 = iconIndex46 + 1;
      achievements46.RegisterIconIndex("ICE_SCREAM", iconIndex46);
      AchievementManager achievements47 = Main.Achievements;
      int iconIndex47 = num47;
      int num48 = iconIndex47 + 1;
      achievements47.RegisterIconIndex("SLIPPERY_SHINOBI", iconIndex47);
      AchievementManager achievements48 = Main.Achievements;
      int iconIndex48 = num48;
      int num49 = iconIndex48 + 1;
      achievements48.RegisterIconIndex("STICKY_SITUATION", iconIndex48);
      AchievementManager achievements49 = Main.Achievements;
      int iconIndex49 = num49;
      int num50 = iconIndex49 + 1;
      achievements49.RegisterIconIndex("REAL_ESTATE_AGENT", iconIndex49);
      AchievementManager achievements50 = Main.Achievements;
      int iconIndex50 = num50;
      int num51 = iconIndex50 + 1;
      achievements50.RegisterIconIndex("NOT_THE_BEES", iconIndex50);
      AchievementManager achievements51 = Main.Achievements;
      int iconIndex51 = num51;
      int num52 = iconIndex51 + 1;
      achievements51.RegisterIconIndex("JEEPERS_CREEPERS", iconIndex51);
      AchievementManager achievements52 = Main.Achievements;
      int iconIndex52 = num52;
      int num53 = iconIndex52 + 1;
      achievements52.RegisterIconIndex("FUNKYTOWN", iconIndex52);
      AchievementManager achievements53 = Main.Achievements;
      int iconIndex53 = num53;
      int num54 = iconIndex53 + 1;
      achievements53.RegisterIconIndex("INTO_ORBIT", iconIndex53);
      AchievementManager achievements54 = Main.Achievements;
      int iconIndex54 = num54;
      int num55 = iconIndex54 + 1;
      achievements54.RegisterIconIndex("ROCK_BOTTOM", iconIndex54);
      AchievementManager achievements55 = Main.Achievements;
      int iconIndex55 = num55;
      int num56 = iconIndex55 + 1;
      achievements55.RegisterIconIndex("MECHA_MAYHEM", iconIndex55);
      AchievementManager achievements56 = Main.Achievements;
      int iconIndex56 = num56;
      int num57 = iconIndex56 + 1;
      achievements56.RegisterIconIndex("GELATIN_WORLD_TOUR", iconIndex56);
      AchievementManager achievements57 = Main.Achievements;
      int iconIndex57 = num57;
      int num58 = iconIndex57 + 1;
      achievements57.RegisterIconIndex("FASHION_STATEMENT", iconIndex57);
      AchievementManager achievements58 = Main.Achievements;
      int iconIndex58 = num58;
      int num59 = iconIndex58 + 1;
      achievements58.RegisterIconIndex("VEHICULAR_MANSLAUGHTER", iconIndex58);
      AchievementManager achievements59 = Main.Achievements;
      int iconIndex59 = num59;
      int num60 = iconIndex59 + 1;
      achievements59.RegisterIconIndex("BULLDOZER", iconIndex59);
      AchievementManager achievements60 = Main.Achievements;
      int iconIndex60 = num60;
      int num61 = iconIndex60 + 1;
      achievements60.RegisterIconIndex("THERE_ARE_SOME_WHO_CALL_HIM", iconIndex60);
      AchievementManager achievements61 = Main.Achievements;
      int iconIndex61 = num61;
      int num62 = iconIndex61 + 1;
      achievements61.RegisterIconIndex("DECEIVER_OF_FOOLS", iconIndex61);
      AchievementManager achievements62 = Main.Achievements;
      int iconIndex62 = num62;
      int num63 = iconIndex62 + 1;
      achievements62.RegisterIconIndex("SWORD_OF_THE_HERO", iconIndex62);
      AchievementManager achievements63 = Main.Achievements;
      int iconIndex63 = num63;
      int num64 = iconIndex63 + 1;
      achievements63.RegisterIconIndex("LUCKY_BREAK", iconIndex63);
      AchievementManager achievements64 = Main.Achievements;
      int iconIndex64 = num64;
      int num65 = iconIndex64 + 1;
      achievements64.RegisterIconIndex("THROWING_LINES", iconIndex64);
      AchievementManager achievements65 = Main.Achievements;
      int iconIndex65 = num65;
      int num66 = iconIndex65 + 1;
      achievements65.RegisterIconIndex("DYE_HARD", iconIndex65);
      AchievementManager achievements66 = Main.Achievements;
      int iconIndex66 = num66;
      int num67 = iconIndex66 + 1;
      achievements66.RegisterIconIndex("FREQUENT_FLYER", iconIndex66);
      AchievementManager achievements67 = Main.Achievements;
      int iconIndex67 = num67;
      int num68 = iconIndex67 + 1;
      achievements67.RegisterIconIndex("THE_CAVALRY", iconIndex67);
      AchievementManager achievements68 = Main.Achievements;
      int iconIndex68 = num68;
      int num69 = iconIndex68 + 1;
      achievements68.RegisterIconIndex("COMPLETELY_AWESOME", iconIndex68);
      AchievementManager achievements69 = Main.Achievements;
      int iconIndex69 = num69;
      int num70 = iconIndex69 + 1;
      achievements69.RegisterIconIndex("TIL_DEATH", iconIndex69);
      AchievementManager achievements70 = Main.Achievements;
      int iconIndex70 = num70;
      int num71 = iconIndex70 + 1;
      achievements70.RegisterIconIndex("ARCHAEOLOGIST", iconIndex70);
      AchievementManager achievements71 = Main.Achievements;
      int iconIndex71 = num71;
      int num72 = iconIndex71 + 1;
      achievements71.RegisterIconIndex("PRETTY_IN_PINK", iconIndex71);
      AchievementManager achievements72 = Main.Achievements;
      int iconIndex72 = num72;
      int num73 = iconIndex72 + 1;
      achievements72.RegisterIconIndex("RAINBOWS_AND_UNICORNS", iconIndex72);
      AchievementManager achievements73 = Main.Achievements;
      int iconIndex73 = num73;
      int num74 = iconIndex73 + 1;
      achievements73.RegisterIconIndex("YOU_AND_WHAT_ARMY", iconIndex73);
      AchievementManager achievements74 = Main.Achievements;
      int iconIndex74 = num74;
      int num75 = iconIndex74 + 1;
      achievements74.RegisterIconIndex("PRISMANCER", iconIndex74);
      AchievementManager achievements75 = Main.Achievements;
      int iconIndex75 = num75;
      int num76 = iconIndex75 + 1;
      achievements75.RegisterIconIndex("IT_CAN_TALK", iconIndex75);
      AchievementManager achievements76 = Main.Achievements;
      int iconIndex76 = num76;
      int num77 = iconIndex76 + 1;
      achievements76.RegisterIconIndex("WATCH_YOUR_STEP", iconIndex76);
      AchievementManager achievements77 = Main.Achievements;
      int iconIndex77 = num77;
      int num78 = iconIndex77 + 1;
      achievements77.RegisterIconIndex("MARATHON_MEDALIST", iconIndex77);
      AchievementManager achievements78 = Main.Achievements;
      int iconIndex78 = num78;
      int num79 = iconIndex78 + 1;
      achievements78.RegisterIconIndex("GLORIOUS_GOLDEN_POLE", iconIndex78);
      AchievementManager achievements79 = Main.Achievements;
      int iconIndex79 = num79;
      int num80 = iconIndex79 + 1;
      achievements79.RegisterIconIndex("SERVANT_IN_TRAINING", iconIndex79);
      AchievementManager achievements80 = Main.Achievements;
      int iconIndex80 = num80;
      int num81 = iconIndex80 + 1;
      achievements80.RegisterIconIndex("GOOD_LITTLE_SLAVE", iconIndex80);
      AchievementManager achievements81 = Main.Achievements;
      int iconIndex81 = num81;
      int num82 = iconIndex81 + 1;
      achievements81.RegisterIconIndex("TROUT_MONKEY", iconIndex81);
      AchievementManager achievements82 = Main.Achievements;
      int iconIndex82 = num82;
      int num83 = iconIndex82 + 1;
      achievements82.RegisterIconIndex("FAST_AND_FISHIOUS", iconIndex82);
      AchievementManager achievements83 = Main.Achievements;
      int iconIndex83 = num83;
      int num84 = iconIndex83 + 1;
      achievements83.RegisterIconIndex("SUPREME_HELPER_MINION", iconIndex83);
      AchievementManager achievements84 = Main.Achievements;
      int iconIndex84 = num84;
      int num85 = iconIndex84 + 1;
      achievements84.RegisterIconIndex("TOPPED_OFF", iconIndex84);
      AchievementManager achievements85 = Main.Achievements;
      int iconIndex85 = num85;
      int num86 = iconIndex85 + 1;
      achievements85.RegisterIconIndex("SLAYER_OF_WORLDS", iconIndex85);
      AchievementManager achievements86 = Main.Achievements;
      int iconIndex86 = num86;
      int num87 = iconIndex86 + 1;
      achievements86.RegisterIconIndex("YOU_CAN_DO_IT", iconIndex86);
      AchievementManager achievements87 = Main.Achievements;
      int iconIndex87 = num87;
      int num88 = iconIndex87 + 1;
      achievements87.RegisterIconIndex("SICK_THROW", iconIndex87);
      AchievementManager achievements88 = Main.Achievements;
      int iconIndex88 = num88;
      int num89 = iconIndex88 + 1;
      achievements88.RegisterIconIndex("MATCHING_ATTIRE", iconIndex88);
      AchievementManager achievements89 = Main.Achievements;
      int iconIndex89 = num89;
      int num90 = iconIndex89 + 1;
      achievements89.RegisterIconIndex("BENCHED", iconIndex89);
      AchievementCategory category1 = AchievementCategory.Slayer;
      Main.Achievements.RegisterAchievementCategory("EYE_ON_YOU", category1);
      Main.Achievements.RegisterAchievementCategory("SLIPPERY_SHINOBI", category1);
      Main.Achievements.RegisterAchievementCategory("WORM_FODDER", category1);
      Main.Achievements.RegisterAchievementCategory("MASTERMIND", category1);
      Main.Achievements.RegisterAchievementCategory("STING_OPERATION", category1);
      Main.Achievements.RegisterAchievementCategory("BONED", category1);
      Main.Achievements.RegisterAchievementCategory("STILL_HUNGRY", category1);
      Main.Achievements.RegisterAchievementCategory("BUCKETS_OF_BOLTS", category1);
      Main.Achievements.RegisterAchievementCategory("THE_GREAT_SOUTHERN_PLANTKILL", category1);
      Main.Achievements.RegisterAchievementCategory("LIHZAHRDIAN_IDOL", category1);
      Main.Achievements.RegisterAchievementCategory("FISH_OUT_OF_WATER", category1);
      Main.Achievements.RegisterAchievementCategory("OBSESSIVE_DEVOTION", category1);
      Main.Achievements.RegisterAchievementCategory("STAR_DESTROYER", category1);
      Main.Achievements.RegisterAchievementCategory("CHAMPION_OF_TERRARIA", category1);
      Main.Achievements.RegisterAchievementCategory("GOBLIN_PUNTER", category1);
      Main.Achievements.RegisterAchievementCategory("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", category1);
      Main.Achievements.RegisterAchievementCategory("WALK_THE_PLANK", category1);
      Main.Achievements.RegisterAchievementCategory("BALEFUL_HARVEST", category1);
      Main.Achievements.RegisterAchievementCategory("ICE_SCREAM", category1);
      Main.Achievements.RegisterAchievementCategory("TIN_FOIL_HATTER", category1);
      Main.Achievements.RegisterAchievementCategory("TIL_DEATH", category1);
      Main.Achievements.RegisterAchievementCategory("THERE_ARE_SOME_WHO_CALL_HIM", category1);
      Main.Achievements.RegisterAchievementCategory("ARCHAEOLOGIST", category1);
      Main.Achievements.RegisterAchievementCategory("PRETTY_IN_PINK", category1);
      Main.Achievements.RegisterAchievementCategory("DECEIVER_OF_FOOLS", category1);
      Main.Achievements.RegisterAchievementCategory("VEHICULAR_MANSLAUGHTER", category1);
      AchievementCategory category2 = AchievementCategory.Explorer;
      Main.Achievements.RegisterAchievementCategory("SMASHING_POPPET", category2);
      Main.Achievements.RegisterAchievementCategory("BEGONE_EVIL", category2);
      Main.Achievements.RegisterAchievementCategory("ITS_HARD", category2);
      Main.Achievements.RegisterAchievementCategory("FUNKYTOWN", category2);
      Main.Achievements.RegisterAchievementCategory("WATCH_YOUR_STEP", category2);
      Main.Achievements.RegisterAchievementCategory("YOU_CAN_DO_IT", category2);
      Main.Achievements.RegisterAchievementCategory("BLOODBATH", category2);
      Main.Achievements.RegisterAchievementCategory("KILL_THE_SUN", category2);
      Main.Achievements.RegisterAchievementCategory("STICKY_SITUATION", category2);
      Main.Achievements.RegisterAchievementCategory("NO_HOBO", category2);
      Main.Achievements.RegisterAchievementCategory("IT_CAN_TALK", category2);
      Main.Achievements.RegisterAchievementCategory("HEART_BREAKER", category2);
      Main.Achievements.RegisterAchievementCategory("I_AM_LOOT", category2);
      Main.Achievements.RegisterAchievementCategory("ROBBING_THE_GRAVE", category2);
      Main.Achievements.RegisterAchievementCategory("GET_A_LIFE", category2);
      Main.Achievements.RegisterAchievementCategory("JEEPERS_CREEPERS", category2);
      Main.Achievements.RegisterAchievementCategory("WHERES_MY_HONEY", category2);
      Main.Achievements.RegisterAchievementCategory("DUNGEON_HEIST", category2);
      Main.Achievements.RegisterAchievementCategory("BIG_BOOTY", category2);
      Main.Achievements.RegisterAchievementCategory("ITS_GETTING_HOT_IN_HERE", category2);
      Main.Achievements.RegisterAchievementCategory("INTO_ORBIT", category2);
      Main.Achievements.RegisterAchievementCategory("ROCK_BOTTOM", category2);
      Main.Achievements.RegisterAchievementCategory("OOO_SHINY", category2);
      Main.Achievements.RegisterAchievementCategory("EXTRA_SHINY", category2);
      Main.Achievements.RegisterAchievementCategory("PHOTOSYNTHESIS", category2);
      AchievementCategory category3 = AchievementCategory.Challenger;
      Main.Achievements.RegisterAchievementCategory("GELATIN_WORLD_TOUR", category3);
      Main.Achievements.RegisterAchievementCategory("SLAYER_OF_WORLDS", category3);
      Main.Achievements.RegisterAchievementCategory("REAL_ESTATE_AGENT", category3);
      Main.Achievements.RegisterAchievementCategory("YOU_AND_WHAT_ARMY", category3);
      Main.Achievements.RegisterAchievementCategory("TOPPED_OFF", category3);
      Main.Achievements.RegisterAchievementCategory("MECHA_MAYHEM", category3);
      Main.Achievements.RegisterAchievementCategory("BULLDOZER", category3);
      Main.Achievements.RegisterAchievementCategory("NOT_THE_BEES", category3);
      Main.Achievements.RegisterAchievementCategory("RAINBOWS_AND_UNICORNS", category3);
      Main.Achievements.RegisterAchievementCategory("THROWING_LINES", category3);
      Main.Achievements.RegisterAchievementCategory("FREQUENT_FLYER", category3);
      Main.Achievements.RegisterAchievementCategory("LUCKY_BREAK", category3);
      Main.Achievements.RegisterAchievementCategory("MARATHON_MEDALIST", category3);
      Main.Achievements.RegisterAchievementCategory("SERVANT_IN_TRAINING", category3);
      Main.Achievements.RegisterAchievementCategory("GOOD_LITTLE_SLAVE", category3);
      Main.Achievements.RegisterAchievementCategory("TROUT_MONKEY", category3);
      Main.Achievements.RegisterAchievementCategory("FAST_AND_FISHIOUS", category3);
      Main.Achievements.RegisterAchievementCategory("SUPREME_HELPER_MINION", category3);
      AchievementCategory category4 = AchievementCategory.Collector;
      Main.Achievements.RegisterAchievementCategory("OBTAIN_HAMMER", category4);
      Main.Achievements.RegisterAchievementCategory("BENCHED", category4);
      Main.Achievements.RegisterAchievementCategory("HEAVY_METAL", category4);
      Main.Achievements.RegisterAchievementCategory("STAR_POWER", category4);
      Main.Achievements.RegisterAchievementCategory("MINER_FOR_FIRE", category4);
      Main.Achievements.RegisterAchievementCategory("HEAD_IN_THE_CLOUDS", category4);
      Main.Achievements.RegisterAchievementCategory("DRAX_ATTAX", category4);
      Main.Achievements.RegisterAchievementCategory("PRISMANCER", category4);
      Main.Achievements.RegisterAchievementCategory("SWORD_OF_THE_HERO", category4);
      Main.Achievements.RegisterAchievementCategory("HOLD_ON_TIGHT", category4);
      Main.Achievements.RegisterAchievementCategory("THE_CAVALRY", category4);
      Main.Achievements.RegisterAchievementCategory("DYE_HARD", category4);
      Main.Achievements.RegisterAchievementCategory("MATCHING_ATTIRE", category4);
      Main.Achievements.RegisterAchievementCategory("FASHION_STATEMENT", category4);
      Main.Achievements.RegisterAchievementCategory("COMPLETELY_AWESOME", category4);
      Main.Achievements.RegisterAchievementCategory("TIMBER", category4);
      Main.Achievements.RegisterAchievementCategory("SICK_THROW", category4);
      Main.Achievements.RegisterAchievementCategory("GLORIOUS_GOLDEN_POLE", category4);
      Main.Achievements.RegisterAchievementCategory("TEMPLE_RAIDER", category4);
      Main.Achievements.RegisterAchievementCategory("LIKE_A_BOSS", category4);
      Main.Achievements.Load();
      Main.Achievements.OnAchievementCompleted += new Achievement.AchievementCompleted(AchievementInitializer.OnAchievementCompleted);
      AchievementsHelper.Initialize();
    }

    private static void OnAchievementCompleted(Achievement achievement)
    {
      Main.NewText(Language.GetTextValue("Achievements.Completed", (object) AchievementTagHandler.GenerateTag(achievement)));
      if (SoundEngine.FindActiveSound((SoundStyle) SoundID.AchievementComplete) != null)
        return;
      SoundEngine.PlayTrackedSound((SoundStyle) SoundID.AchievementComplete);
    }
  }
}
