// Decompiled with JetBrains decompiler
// Type: Terraria.GameContent.TextureAssets
// Assembly: Terraria, Version=1.4.0.5, Culture=neutral, PublicKeyToken=null
// MVID: 67F9E73E-0A81-4937-A22C-5515CD405A83
// Assembly location: C:\Users\mikeyisbaeyt\Downloads\depotdownloader-2.4.5\depots\105601\6707058\Terraria.exe

using Microsoft.Xna.Framework.Graphics;
using ReLogic.Content;

namespace Terraria.GameContent
{
  public static class TextureAssets
  {
    public static Asset<Texture2D>[] InfoIcon = new Asset<Texture2D>[14];
    public static Asset<Texture2D>[] WireUi = new Asset<Texture2D>[12];
    public static Asset<Texture2D> BuilderAcc;
    public static Asset<Texture2D> QuicksIcon;
    public static Asset<Texture2D>[] Clothes = new Asset<Texture2D>[6];
    public static Asset<Texture2D>[] MapIcon = new Asset<Texture2D>[9];
    public static Asset<Texture2D>[] Underworld = new Asset<Texture2D>[14];
    public static Asset<Texture2D> MapPing;
    public static Asset<Texture2D> Map;
    public static Asset<Texture2D>[] MapBGs = new Asset<Texture2D>[42];
    public static Asset<Texture2D> Hue;
    public static Asset<Texture2D> FlameRing;
    public static Asset<Texture2D> MapDeath;
    public static Asset<Texture2D> ColorSlider;
    public static Asset<Texture2D> ColorBar;
    public static Asset<Texture2D> ColorBlip;
    public static Asset<Texture2D> SmartDig;
    public static Asset<Texture2D> ColorHighlight;
    public static Asset<Texture2D> TileCrack;
    public static Asset<Texture2D> LockOnCursor;
    public static Asset<Texture2D> IceBarrier;
    public static Asset<Texture2D>[] ChestStack = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] NpcHead = new Asset<Texture2D>[45];
    public static Asset<Texture2D>[] NpcHeadBoss = new Asset<Texture2D>[39];
    public static Asset<Texture2D>[] CraftToggle = new Asset<Texture2D>[4];
    public static Asset<Texture2D>[] InventorySort = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] TextGlyph = new Asset<Texture2D>[1];
    public static Asset<Texture2D>[] HotbarRadial = new Asset<Texture2D>[3];
    public static Asset<Texture2D> CraftUpButton;
    public static Asset<Texture2D> CraftDownButton;
    public static Asset<Texture2D> ScrollLeftButton;
    public static Asset<Texture2D> ScrollRightButton;
    public static Asset<Texture2D> Frozen;
    public static Asset<Texture2D> MagicPixel;
    public static Asset<Texture2D> SettingsPanel;
    public static Asset<Texture2D> SettingsPanel2;
    public static Asset<Texture2D>[] Dest = new Asset<Texture2D>[3];
    public static Asset<Texture2D>[] Gem = new Asset<Texture2D>[7];
    public static Asset<Texture2D>[] RudolphMount = new Asset<Texture2D>[3];
    public static Asset<Texture2D> BunnyMount;
    public static Asset<Texture2D> PigronMount;
    public static Asset<Texture2D> SlimeMount;
    public static Asset<Texture2D> MinecartMount;
    public static Asset<Texture2D> TurtleMount;
    public static Asset<Texture2D> DesertMinecartMount;
    public static Asset<Texture2D> FishMinecartMount;
    public static Asset<Texture2D>[] BeeMount = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] UfoMount = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] DrillMount = new Asset<Texture2D>[6];
    public static Asset<Texture2D>[] ScutlixMount = new Asset<Texture2D>[3];
    public static Asset<Texture2D> UnicornMount;
    public static Asset<Texture2D> BasiliskMount;
    public static Asset<Texture2D>[] MinecartMechMount = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] CuteFishronMount = new Asset<Texture2D>[2];
    public static Asset<Texture2D> MinecartWoodMount;
    public static Asset<Texture2D>[] Wings = new Asset<Texture2D>[47];
    public static Asset<Texture2D>[] ArmorHead = new Asset<Texture2D>[266];
    public static Asset<Texture2D>[] ArmorBody = new Asset<Texture2D>[235];
    public static Asset<Texture2D>[] ArmorBodyComposite = new Asset<Texture2D>[235];
    public static Asset<Texture2D>[] FemaleBody = new Asset<Texture2D>[235];
    public static Asset<Texture2D>[] ArmorArm = new Asset<Texture2D>[235];
    public static Asset<Texture2D>[] ArmorLeg = new Asset<Texture2D>[218];
    public static Asset<Texture2D>[] AccHandsOn = new Asset<Texture2D>[22];
    public static Asset<Texture2D>[] AccHandsOnComposite = new Asset<Texture2D>[22];
    public static Asset<Texture2D>[] AccHandsOff = new Asset<Texture2D>[14];
    public static Asset<Texture2D>[] AccHandsOffComposite = new Asset<Texture2D>[14];
    public static Asset<Texture2D>[] AccBack = new Asset<Texture2D>[30];
    public static Asset<Texture2D>[] AccFront = new Asset<Texture2D>[9];
    public static Asset<Texture2D>[] AccShoes = new Asset<Texture2D>[25];
    public static Asset<Texture2D>[] AccWaist = new Asset<Texture2D>[17];
    public static Asset<Texture2D>[] AccShield = new Asset<Texture2D>[10];
    public static Asset<Texture2D>[] AccNeck = new Asset<Texture2D>[11];
    public static Asset<Texture2D>[] AccFace = new Asset<Texture2D>[16];
    public static Asset<Texture2D>[] AccBalloon = new Asset<Texture2D>[18];
    public static Asset<Texture2D> Pulley;
    public static Asset<Texture2D>[] XmasTree = new Asset<Texture2D>[5];
    public static Asset<Texture2D>[] Flames = new Asset<Texture2D>[17];
    public static Asset<Texture2D> Timer;
    public static Asset<Texture2D>[] Reforge = new Asset<Texture2D>[2];
    public static Asset<Texture2D> EmoteMenuButton;
    public static Asset<Texture2D> BestiaryMenuButton;
    public static Asset<Texture2D> WallOutline;
    public static Asset<Texture2D> Actuator;
    public static Asset<Texture2D> Wire;
    public static Asset<Texture2D> Wire2;
    public static Asset<Texture2D> Wire3;
    public static Asset<Texture2D> Wire4;
    public static Asset<Texture2D> WireNew;
    public static Asset<Texture2D>[] Camera = new Asset<Texture2D>[8];
    public static Asset<Texture2D> FlyingCarpet;
    public static Asset<Texture2D> Grid;
    public static Asset<Texture2D> LightDisc;
    public static Asset<Texture2D> EyeLaser;
    public static Asset<Texture2D> BoneEyes;
    public static Asset<Texture2D> BoneLaser;
    public static Asset<Texture2D> Trash;
    public static Asset<Texture2D> FishingLine;
    public static Asset<Texture2D> Beetle;
    public static Asset<Texture2D> Probe;
    public static Asset<Texture2D> EyeLaserSmall;
    public static Asset<Texture2D> XmasLight;
    public static Asset<Texture2D>[] Golem = new Asset<Texture2D>[4];
    public static Asset<Texture2D> Confuse;
    public static Asset<Texture2D> SunOrb;
    public static Asset<Texture2D> SunAltar;
    public static Asset<Texture2D>[] Chains = new Asset<Texture2D>[17];
    public static Asset<Texture2D> Chain;
    public static Asset<Texture2D>[] GemChain = new Asset<Texture2D>[7];
    public static Asset<Texture2D> Chain2;
    public static Asset<Texture2D> Chain3;
    public static Asset<Texture2D> Chain4;
    public static Asset<Texture2D> Chain5;
    public static Asset<Texture2D> Chain6;
    public static Asset<Texture2D> Chain7;
    public static Asset<Texture2D> Chain8;
    public static Asset<Texture2D> Chain9;
    public static Asset<Texture2D> Chain10;
    public static Asset<Texture2D> Chain11;
    public static Asset<Texture2D> Chain12;
    public static Asset<Texture2D> Chain13;
    public static Asset<Texture2D> Chain14;
    public static Asset<Texture2D> Chain15;
    public static Asset<Texture2D> Chain16;
    public static Asset<Texture2D> Chain17;
    public static Asset<Texture2D> Chain18;
    public static Asset<Texture2D> Chain19;
    public static Asset<Texture2D> Chain20;
    public static Asset<Texture2D> Chain21;
    public static Asset<Texture2D> Chain22;
    public static Asset<Texture2D> Chain23;
    public static Asset<Texture2D> Chain24;
    public static Asset<Texture2D> Chain25;
    public static Asset<Texture2D> Chain26;
    public static Asset<Texture2D> Chain27;
    public static Asset<Texture2D> Chain28;
    public static Asset<Texture2D> Chain29;
    public static Asset<Texture2D> Chain30;
    public static Asset<Texture2D> Chain31;
    public static Asset<Texture2D> Chain32;
    public static Asset<Texture2D> Chain33;
    public static Asset<Texture2D> Chain34;
    public static Asset<Texture2D> Chain35;
    public static Asset<Texture2D> Chain36;
    public static Asset<Texture2D> Chain37;
    public static Asset<Texture2D> Chain38;
    public static Asset<Texture2D> Chain39;
    public static Asset<Texture2D> Chain40;
    public static Asset<Texture2D> Chain41;
    public static Asset<Texture2D> Chain42;
    public static Asset<Texture2D> Chain43;
    public static Asset<Texture2D> Hb1;
    public static Asset<Texture2D> Hb2;
    public static Asset<Texture2D> Chaos;
    public static Asset<Texture2D> Cd;
    public static Asset<Texture2D> Wof;
    public static Asset<Texture2D> BoneArm;
    public static Asset<Texture2D> BoneArm2;
    public static Asset<Texture2D> PumpkingArm;
    public static Asset<Texture2D> PumpkingCloak;
    public static Asset<Texture2D>[] EquipPage = new Asset<Texture2D>[11];
    public static Asset<Texture2D> HouseBanner;
    public static Asset<Texture2D>[] Pvp = new Asset<Texture2D>[3];
    public static Asset<Texture2D>[] NpcToggle = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] HbLock = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] blockReplaceIcon = new Asset<Texture2D>[2];
    public static Asset<Texture2D>[] Buff = new Asset<Texture2D>[323];
    public static Asset<Texture2D>[] Item = new Asset<Texture2D>[5045];
    public static Asset<Texture2D>[] ItemFlame = new Asset<Texture2D>[5045];
    public static Asset<Texture2D>[] Npc = new Asset<Texture2D>[663];
    public static Asset<Texture2D>[] Projectile = new Asset<Texture2D>[950];
    public static Asset<Texture2D>[] Gore = new Asset<Texture2D>[1269];
    public static Asset<Texture2D>[] BackPack = new Asset<Texture2D>[9];
    public static Asset<Texture2D> Rain;
    public static Asset<Texture2D>[] GlowMask = new Asset<Texture2D>[301];
    public static Asset<Texture2D>[] Extra = new Asset<Texture2D>[212];
    public static Asset<Texture2D>[] HighlightMask = new Asset<Texture2D>[623];
    public static Asset<Texture2D>[] Coin = new Asset<Texture2D>[4];
    public static Asset<Texture2D>[] Cursors = new Asset<Texture2D>[18];
    public static Asset<Texture2D> CursorRadial;
    public static Asset<Texture2D> Dust;
    public static Asset<Texture2D> Sun;
    public static Asset<Texture2D> Sun2;
    public static Asset<Texture2D> Sun3;
    public static Asset<Texture2D>[] Moon = new Asset<Texture2D>[9];
    public static Asset<Texture2D> SmileyMoon;
    public static Asset<Texture2D> PumpkinMoon;
    public static Asset<Texture2D> SnowMoon;
    public static Asset<Texture2D> OneDropLogo;
    public static Asset<Texture2D>[] Tile = new Asset<Texture2D>[623];
    public static Asset<Texture2D> BlackTile;
    public static Asset<Texture2D>[] Wall = new Asset<Texture2D>[316];
    public static Asset<Texture2D>[] Background = new Asset<Texture2D>[298];
    public static Asset<Texture2D>[] Cloud = new Asset<Texture2D>[37];
    public static Asset<Texture2D>[] Star = new Asset<Texture2D>[4];
    public static Asset<Texture2D>[] Liquid = new Asset<Texture2D>[13];
    public static Asset<Texture2D>[] LiquidSlope = new Asset<Texture2D>[13];
    public static Asset<Texture2D> Heart;
    public static Asset<Texture2D> Heart2;
    public static Asset<Texture2D> Mana;
    public static Asset<Texture2D> Bubble;
    public static Asset<Texture2D> Flame;
    public static Asset<Texture2D>[] TreeTop = new Asset<Texture2D>[31];
    public static Asset<Texture2D>[] TreeBranch = new Asset<Texture2D>[31];
    public static Asset<Texture2D>[] Wood = new Asset<Texture2D>[7];
    public static Asset<Texture2D> ShroomCap;
    public static Asset<Texture2D> InventoryBack;
    public static Asset<Texture2D> InventoryBack2;
    public static Asset<Texture2D> InventoryBack3;
    public static Asset<Texture2D> InventoryBack4;
    public static Asset<Texture2D> InventoryBack5;
    public static Asset<Texture2D> InventoryBack6;
    public static Asset<Texture2D> InventoryBack7;
    public static Asset<Texture2D> InventoryBack8;
    public static Asset<Texture2D> InventoryBack9;
    public static Asset<Texture2D> InventoryBack10;
    public static Asset<Texture2D> InventoryBack11;
    public static Asset<Texture2D> InventoryBack12;
    public static Asset<Texture2D> InventoryBack13;
    public static Asset<Texture2D> InventoryBack14;
    public static Asset<Texture2D> InventoryBack15;
    public static Asset<Texture2D> InventoryBack16;
    public static Asset<Texture2D> InventoryBack17;
    public static Asset<Texture2D> InventoryBack18;
    public static Asset<Texture2D> HairStyleBack;
    public static Asset<Texture2D> ClothesStyleBack;
    public static Asset<Texture2D> InventoryTickOn;
    public static Asset<Texture2D> InventoryTickOff;
    public static Asset<Texture2D> SplashTexture16x9;
    public static Asset<Texture2D> SplashTexture4x3;
    public static Asset<Texture2D> SplashTextureLegoBack;
    public static Asset<Texture2D> SplashTextureLegoResonanace;
    public static Asset<Texture2D> SplashTextureLegoTree;
    public static Asset<Texture2D> SplashTextureLegoFront;
    public static Asset<Texture2D> Logo;
    public static Asset<Texture2D> Logo2;
    public static Asset<Texture2D> Logo3;
    public static Asset<Texture2D> Logo4;
    public static Asset<Texture2D> TextBack;
    public static Asset<Texture2D> Chat;
    public static Asset<Texture2D> Chat2;
    public static Asset<Texture2D> ChatBack;
    public static Asset<Texture2D> Team;
    public static Asset<Texture2D> Re;
    public static Asset<Texture2D> Ra;
    public static Asset<Texture2D> Splash;
    public static Asset<Texture2D> Fade;
    public static Asset<Texture2D> Ninja;
    public static Asset<Texture2D> AntLion;
    public static Asset<Texture2D> SpikeBase;
    public static Asset<Texture2D> Ghost;
    public static Asset<Texture2D> EvilCactus;
    public static Asset<Texture2D> GoodCactus;
    public static Asset<Texture2D> CrimsonCactus;
    public static Asset<Texture2D> WraithEye;
    public static Asset<Texture2D> Firefly;
    public static Asset<Texture2D> FireflyJar;
    public static Asset<Texture2D> Lightningbug;
    public static Asset<Texture2D> LightningbugJar;
    public static Asset<Texture2D>[] JellyfishBowl = new Asset<Texture2D>[3];
    public static Asset<Texture2D> GlowSnail;
    public static Asset<Texture2D> IceQueen;
    public static Asset<Texture2D> SantaTank;
    public static Asset<Texture2D> ReaperEye;
    public static Asset<Texture2D> JackHat;
    public static Asset<Texture2D> TreeFace;
    public static Asset<Texture2D> PumpkingFace;
    public static Asset<Texture2D> DukeFishron;
    public static Asset<Texture2D> MiniMinotaur;
    public static Asset<Texture2D>[,] Players;
    public static Asset<Texture2D>[] PlayerHair = new Asset<Texture2D>[162];
    public static Asset<Texture2D>[] PlayerHairAlt = new Asset<Texture2D>[162];
    public static Asset<Texture2D> LoadingSunflower;
    public static Asset<Texture2D> GolfSwingBarPanel;
    public static Asset<Texture2D> GolfSwingBarFill;
    public static Asset<Texture2D> SpawnPoint;
    public static Asset<Texture2D> SpawnBed;
    public static Asset<Texture2D> GolfBallArrow;
    public static Asset<Texture2D> GolfBallArrowShadow;
    public static Asset<Texture2D> GolfBallOutline;

    public static class RenderTargets
    {
      public static PlayerRainbowWingsTextureContent PlayerRainbowWings;
      public static PlayerTitaniumStormBuffTextureContent PlayerTitaniumStormBuff;
      public static PlayerQueenSlimeMountTextureContent QueenSlimeMount;
    }
  }
}
